<?php
/**
 * AMP (Accelerated Mobile Pages) module (lean frontend class).
 *
 * @package GTM4WP
 * @author Thomas Geiger
 * @author Vincent Koc <https://github.com/koconder/>
 * @copyright 2013- Geiger Tamás e.v. (Thomas Geiger s.e.)
 * @license GNU General Public License, version 3
 */

namespace GTM4WP\Modules\Amp;

use GTM4WP\Frontend\ContainerCode;
use GTM4WP\Module\AbstractModule;
use GTM4WP\Plugin;

defined( 'ABSPATH' ) || exit;

/**
 * Adds the AMP GTM snippet to AMP pages generated by the amp-wp plugin.
 * Port of integration/amp.php from 1.x.
 *
 * Note: the 1.x body injection checked the never-populated
 * $gtm4wp_datalayer_json global and therefore never ran; 2.0 checks the
 * compiled data layer instead, making the amp-analytics injection work
 * as originally intended.
 */
final class AmpModule extends AbstractModule {

	/**
	 * Whether the amp-analytics component script has been injected into the head.
	 *
	 * @var bool
	 */
	private bool $header_injected = false;

	/**
	 * Whether the amp-analytics snippet has been injected into the body.
	 *
	 * @var bool
	 */
	private bool $body_injected = false;

	/**
	 * Module id.
	 *
	 * @return string
	 */
	public function id(): string {
		return 'amp';
	}

	/**
	 * Option defaults, 1.x compatible.
	 *
	 * @return array<string, mixed>
	 */
	public function defaults(): array {
		return array(
			GTM4WP_OPTION_INTEGRATE_AMPID => '',
		);
	}

	/**
	 * Registers the frontend hooks.
	 *
	 * @return void
	 */
	protected function register_frontend_hooks(): void {
		if ( '' === (string) $this->opt( GTM4WP_OPTION_INTEGRATE_AMPID ) ) {
			return;
		}

		add_filter( ContainerCode::FILTER_AMP_RUNNING, array( $this, 'is_amp_request' ) );

		// Load the AMP-Analytics component script into <head>.
		add_action( 'amp_post_template_data', array( $this, 'check_component_script' ) );

		// Load the GTM code processing to gain the GTM data layer.
		add_action( 'amp_post_template_head', array( $this, 'render_header_begin' ) );
		add_action( 'amp_post_template_head', array( $this, 'render_header_top' ), 1 );

		// Publish the GTM code and data layer.
		add_action( 'amp_post_template_body_open', array( $this, 'render_amp_gtm_code' ) );
		add_action( 'amp_post_template_footer', array( $this, 'render_amp_gtm_code' ) );
	}

	/**
	 * Admin schema class name.
	 *
	 * @return string
	 */
	public function admin_schema(): string {
		return AdminSchema::class;
	}

	/**
	 * Check if we are running AMP.
	 *
	 * @param bool $running Current filter value.
	 * @return bool Returns true if we are running on an AMP page.
	 */
	public function is_amp_request( $running = false ) {
		if ( function_exists( 'is_amp_endpoint' ) && is_amp_endpoint() ) {
			return true;
		}

		return (bool) $running;
	}

	/**
	 * Renders the main container/data layer script block via the core service.
	 *
	 * @return void
	 */
	public function render_header_begin(): void {
		Plugin::instance()->frontend()->container()->header_begin();
	}

	/**
	 * Renders the data layer initialization block via the core service.
	 *
	 * @return void
	 */
	public function render_header_top(): void {
		Plugin::instance()->frontend()->container()->header_top();
	}

	/**
	 * Pre-injection check for AMP Project's amp-analytics component script,
	 * using the amp-wp hook.
	 *
	 * @param array $data AMP Template data.
	 * @return array Returns AMP data array used by amp-wp.
	 */
	public function check_component_script( $data ) {
		// Run once.
		if ( $this->header_injected ) {
			return $data;
		}

		if ( ! empty( $data['amp_analytics'] ) ) {
			// Inject into AMP Plugin to load.
			$data['amp_component_scripts']['amp-analytics'] = 'https://cdn.ampproject.org/v0/amp-analytics-0.1.js';

			$this->header_injected = true;
		} else {
			// Inject manually based on the AMP <head> hook.
			add_action( 'amp_post_template_head', array( $this, 'inject_component_script' ) );
		}

		return $data;
	}

	/**
	 * Manually outputs the amp-analytics component script into the AMP head.
	 *
	 * @return void
	 */
	public function inject_component_script(): void {
		$this->header_injected = true;

		// wp_enqueue_script() can not handle the special script element attributes needed here.
		echo '<script async custom-element="amp-analytics" src="https://cdn.ampproject.org/v0/amp-analytics-0.1.js"></script>'; // phpcs:ignore WordPress.WP.EnqueuedResources.NonEnqueuedScript, WordPress.Security.EscapeOutput.OutputNotEscaped
	}

	/**
	 * Generates the AMP ready Google Tag Manager code.
	 *
	 * @return int|false Returns number of injected snippets, false if no injection.
	 */
	public function render_amp_gtm_code() {
		// Run once.
		if ( $this->body_injected ) {
			return false;
		}

		$this->body_injected = true;

		$datalayer_data = $GLOBALS['gtm4wp_datalayer_data'] ?? array();

		// Check the data layer is loaded from the plugin.
		if ( ! empty( $datalayer_data ) ) {
			// Builds a list of GTM ids.
			$gtm4wp_ampids = explode( ',', (string) $this->opt( GTM4WP_OPTION_INTEGRATE_AMPID ) );

			// Counter used for status return.
			$injected_count = 0;

			if ( count( $gtm4wp_ampids ) > 0 ) {
				foreach ( $gtm4wp_ampids as $gtm4wp_oneampid ) {
					// Docs: https://developers.google.com/analytics/devguides/collection/amp-analytics/.
					echo '<!-- Google Tag Manager --><amp-analytics config="https://www.googletagmanager.com/amp.json?id=' . esc_url_raw( $gtm4wp_oneampid ) . '&gtm.url=SOURCE_URL" data-credentials="include"><script type="application/json">' . wp_json_encode( array( 'vars' => $datalayer_data ), JSON_HEX_TAG ) . '</script></amp-analytics>'; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped

					++$injected_count;
				}

				if ( $injected_count > 0 ) {
					return $injected_count;
				}
			}
		}

		// No injection has occurred.
		return false;
	}
}
