tools:
    php_code_sniffer:
        config:
            standard: WordPress
        sensiolabs_security_checker: true
        external_code_coverage:
        timeout: 2500
build:
    nodes:
        analysis:
            dependencies:
                before:
                    - composer require johnpbloch/wordpress
                    - composer require dealerdirect/phpcodesniffer-composer-installer
                    - composer require squizlabs/php_codesniffer
                    - composer require wp-coding-standards/wpcs
                    - composer require phpcompatibility/php-compatibility
                    - composer require phpcompatibility/phpcompatibility-paragonie
                    - composer require phpcompatibility/phpcompatibility
                    - composer require phpunit/phpunit:^6.1.0
                tests:
                    override:
                    -
                        command: phpcs-run
                        use_website_config: true
                    - php-scrutinizer-run
checks:
    php:
        avoid_closing_tag: false
        avoid_superglobals: false
        no_exit: false
        psr2_control_structure_declaration: false
        variable_existence: false
        verify_access_scope_valid: false
        verify_argument_usable_as_reference: false
        verify_property_names: false
        fix_php_opening_tag: false
        remove_php_closing_tag: false
        no_mixed_inline_html: false
        require_braces_around_control_structures: false
        security_vulnerabilities: false
        coding_standard:
            name: WordPress
    javascript: true
    external_code_coverage: true
filter:
    excluded_paths:
        - tests/
        - integration/whichbrowser/
        - docker/
        - vendor/
        - spec/
    dependency_paths:
        - wordpress/
