<?php
/**
 * Unit tests for the public 1.x constants.
 *
 * @package GTM4WP
 */

namespace GTM4WP\Tests\unit\Compat;

use GTM4WP\Tests\unit\TestCase;

/**
 * The constant VALUES are public API: stored option keys, hook names and
 * placement numbers third-party code and existing sites rely on. Every other
 * test reads them through the constant, so a changed value went red nowhere
 * (T133, TS-21). The table is the literal contract; a new constant gets a row
 * in the same change.
 */
final class ConstantsTest extends TestCase {

	/**
	 * Every constant compat/constants.php defines, with its value.
	 */
	private const VALUES = array(
		'GTM4WP_OPTIONS'                                   => 'gtm4wp-options',
		'GTM4WP_ADMINSLUG'                                 => 'gtm4wp-settings',
		'GTM4WP_OPTION_GTM_CODE'                           => 'gtm-code',
		'GTM4WP_OPTION_GTM_CONTAINERS'                     => 'gtm-containers',
		'GTM4WP_OPTION_GTM_PLACEMENT'                      => 'gtm-code-placement',
		'GTM4WP_OPTION_DATALAYER_NAME'                     => 'gtm-datalayer-variable-name',
		'GTM4WP_OPTION_ENV_GTM_AUTH'                       => 'gtm-env-gtm-auth',
		'GTM4WP_OPTION_ENV_GTM_PREVIEW'                    => 'gtm-env-gtm-preview',
		'GTM4WP_OPTION_LOADEARLY'                          => 'gtm-load-gtm-early',
		'GTM4WP_OPTION_GTMDOMAIN'                          => 'gtm-domain-name',
		'GTM4WP_OPTION_GTMCUSTOMPATH'                      => 'gtm-custom-path',
		'GTM4WP_OPTION_NOGTMFORLOGGEDIN'                   => 'gtm-no-gtm-for-logged-in',
		'GTM4WP_OPTION_NOCONSOLELOG'                       => 'gtm-no-console-log',
		'GTM4WP_OPTION_PRODUCTIONONLY'                     => 'gtm-production-only',
		'GTM4WP_OPTION_INCLUDE_LOGGEDIN'                   => 'include-loggedin',
		'GTM4WP_OPTION_INCLUDE_USERROLE'                   => 'include-userrole',
		'GTM4WP_OPTION_INCLUDE_USERID'                     => 'include-userid',
		'GTM4WP_OPTION_INCLUDE_USEREMAIL'                  => 'include-useremail',
		'GTM4WP_OPTION_INCLUDE_USERREGDATE'                => 'include-userregdate',
		'GTM4WP_OPTION_INCLUDE_USERNAME'                   => 'include-username',
		'GTM4WP_OPTION_INCLUDE_VISITOR_IP'                 => 'include-visitor-ip',
		'GTM4WP_OPTION_INCLUDE_VISITOR_IP_HEADER'          => 'include-visitor-ip-header',
		'GTM4WP_OPTION_INCLUDE_VISITOR_IP_PROXIES'         => 'include-visitor-ip-proxies',
		'GTM4WP_OPTION_INCLUDE_POSTTYPE'                   => 'include-posttype',
		'GTM4WP_OPTION_INCLUDE_CATEGORIES'                 => 'include-categories',
		'GTM4WP_OPTION_INCLUDE_TAGS'                       => 'include-tags',
		'GTM4WP_OPTION_INCLUDE_AUTHORID'                   => 'include-authorid',
		'GTM4WP_OPTION_INCLUDE_AUTHOR'                     => 'include-author',
		'GTM4WP_OPTION_INCLUDE_POSTDATE'                   => 'include-postdate',
		'GTM4WP_OPTION_INCLUDE_POSTTITLE'                  => 'include-posttitle',
		'GTM4WP_OPTION_INCLUDE_POSTCOUNT'                  => 'include-postcount',
		'GTM4WP_OPTION_INCLUDE_POSTID'                     => 'include-postid',
		'GTM4WP_OPTION_INCLUDE_POSTFORMAT'                 => 'include-postformat',
		'GTM4WP_OPTION_INCLUDE_POSTTERMLIST'               => 'include-postterms',
		'GTM4WP_OPTION_INCLUDE_POSTMETA'                   => 'include-postmeta',
		'GTM4WP_OPTION_INCLUDE_POSTMETA_KEYS'              => 'include-postmeta-keys',
		'GTM4WP_OPTION_INCLUDE_SEARCHDATA'                 => 'include-searchdata',
		'GTM4WP_OPTION_INCLUDE_BROWSERDATA'                => 'include-browserdata',
		'GTM4WP_OPTION_INCLUDE_OSDATA'                     => 'include-osdata',
		'GTM4WP_OPTION_INCLUDE_DEVICEDATA'                 => 'include-devicedata',
		'GTM4WP_OPTION_INCLUDE_SITEID'                     => 'include-siteid',
		'GTM4WP_OPTION_INCLUDE_SITENAME'                   => 'include-sitename',
		'GTM4WP_OPTION_INCLUDE_CONTENTWORDCOUNT'           => 'include-content-word-count',
		'GTM4WP_OPTION_INCLUDE_READINGTIME'                => 'include-reading-time',
		'GTM4WP_OPTION_INCLUDE_MODIFIEDDATE'               => 'include-modified-date',
		'GTM4WP_OPTION_INCLUDE_CONTENTAGE'                 => 'include-content-age',
		'GTM4WP_OPTION_INCLUDE_COMMENTCOUNT'               => 'include-comment-count',
		'GTM4WP_OPTION_INCLUDE_PAGETEMPLATE'               => 'include-page-template',
		'GTM4WP_OPTION_INCLUDE_FEATUREDIMAGE'              => 'include-featured-image',
		'GTM4WP_OPTION_INCLUDE_PAGEHIERARCHY'              => 'include-page-hierarchy',
		'GTM4WP_OPTION_INCLUDE_POSTSTICKY'                 => 'include-post-sticky',
		'GTM4WP_OPTION_INCLUDE_PRIMARYCATEGORY'            => 'include-primary-category',
		'GTM4WP_OPTION_INCLUDE_PAGELANGUAGE'               => 'include-page-language',
		'GTM4WP_OPTION_INCLUDE_PARENTCATEGORIES'           => 'include-parent-categories',
		'GTM4WP_OPTION_INCLUDE_MASTERLANGUAGE'             => 'include-master-language',
		'GTM4WP_OPTION_CACHE_SAFE_DATALAYER'               => 'cache-safe-datalayer',
		'GTM4WP_OPTION_INCLUDE_MISCGEOCF'                  => 'include-miscgeo-cloudflare',
		'GTM4WP_OPTION_INCLUDE_MISCGEO'                    => 'include-miscgeo',
		'GTM4WP_OPTION_INCLUDE_MISCGEOAPI'                 => 'geo-apikey',
		'GTM4WP_OPTION_INCLUDE_WEATHER'                    => 'include-weather',
		'GTM4WP_OPTION_INCLUDE_WEATHERUNITS'               => 'weather-weatherunits',
		'GTM4WP_OPTION_INCLUDE_WEATHEROWMAPI'              => 'weather-openweathermap-apikey',
		'GTM4WP_OPTION_EVENTS_FORMMOVE'                    => 'event-form-move',
		'GTM4WP_OPTION_EVENTS_FORMMOVE_FILLEDONLY'         => 'event-form-move-filled-only',
		'GTM4WP_OPTION_EVENTS_NEWUSERREG'                  => 'event-new-user-registration',
		'GTM4WP_OPTION_EVENTS_USERLOGIN'                   => 'event-user-logged-in',
		'GTM4WP_OPTION_EVENTS_YOUTUBE'                     => 'event-youtube',
		'GTM4WP_OPTION_EVENTS_VIMEO'                       => 'event-vimeo',
		'GTM4WP_OPTION_EVENTS_SOUNDCLOUD'                  => 'event-soundcloud',
		'GTM4WP_OPTION_EVENTS_HTML5MEDIA'                  => 'event-html5-media',
		'GTM4WP_OPTION_EVENTS_DAILYMOTION'                 => 'event-dailymotion',
		'GTM4WP_OPTION_EVENTS_DAILYMOTION_PLAYERID'        => 'event-dailymotion-playerid',
		'GTM4WP_OPTION_EVENTS_MIXCLOUD'                    => 'event-mixcloud',
		'GTM4WP_OPTION_EVENTS_CLOUDFLARESTREAM'            => 'event-cloudflare-stream',
		'GTM4WP_OPTION_EVENTS_WISTIA'                      => 'event-wistia',
		'GTM4WP_OPTION_EVENTS_JWPLAYER'                    => 'event-jwplayer',
		'GTM4WP_OPTION_EVENTS_VIDEOPRESS'                  => 'event-videopress',
		'GTM4WP_OPTION_EVENTS_SPOTIFY'                     => 'event-spotify',
		'GTM4WP_OPTION_EVENTS_TWITCH'                      => 'event-twitch',
		'GTM4WP_OPTION_EVENTS_MEDIA_DYNAMIC'               => 'event-media-dynamic',
		'GTM4WP_OPTION_SCROLLER_ENABLED'                   => 'scroller-enabled',
		'GTM4WP_OPTION_SCROLLER_DEBUGMODE'                 => 'scroller-debug-mode',
		'GTM4WP_OPTION_SCROLLER_CALLBACKTIME'              => 'scroller-callback-time',
		'GTM4WP_OPTION_SCROLLER_DISTANCE'                  => 'scroller-distance',
		'GTM4WP_OPTION_SCROLLER_CONTENTID'                 => 'scroller-contentid',
		'GTM4WP_OPTION_SCROLLER_READERTIME'                => 'scroller-readertime',
		'GTM4WP_OPTION_BLACKLIST_ENABLE'                   => 'blacklist-enable',
		'GTM4WP_OPTION_BLACKLIST_SANDBOXED'                => 'blacklist-sandboxed',
		'GTM4WP_OPTION_BLACKLIST_STATUS'                   => 'blacklist-status',
		'GTM4WP_OPTION_INTEGRATE_WPCF7'                    => 'integrate-wpcf7',
		'GTM4WP_OPTION_INTEGRATE_WPCF7_INPUTS'             => 'integrate-wpcf7-inputs',
		'GTM4WP_OPTION_INTEGRATE_WPCF7_GA4EVENTS'          => 'integrate-wpcf7-ga4events',
		'GTM4WP_OPTION_INTEGRATE_WPCF7_MASTERLANGUAGE'     => 'integrate-wpcf7-master-language',
		'GTM4WP_OPTION_INTEGRATE_WCTRACKECOMMERCE'         => 'integrate-woocommerce-track-enhanced-ecommerce',
		'GTM4WP_OPTION_INTEGRATE_WCPRODPERIMPRESSION'      => 'integrate-woocommerce-product-per-impression',
		'GTM4WP_OPTION_INTEGRATE_WCEINCLUDECARTINDL'       => 'integrate-woocommerce-cart-content-in-datalayer',
		'GTM4WP_OPTION_INTEGRATE_WCEECBRANDTAXONOMY'       => 'integrate-woocommerce-brand-taxonomy',
		'GTM4WP_OPTION_INTEGRATE_WCBUSINESSVERTICAL'       => 'integrate-woocommerce-business-vertical',
		'GTM4WP_OPTION_INTEGRATE_WCUSESKU'                 => 'integrate-woocommerce-remarketing-usesku',
		'GTM4WP_OPTION_INTEGRATE_WCVIEWITEMONPARENT'       => 'integrate-woocommerce-view-item-on-parent-product',
		'GTM4WP_OPTION_INTEGRATE_WCUSEFULLCATEGORYPATH'    => 'integrate-woocommerce-use-full-category-path',
		'GTM4WP_OPTION_INTEGRATE_WCREMPRODIDPREFIX'        => 'integrate-woocommerce-remarketing-productidprefix',
		'GTM4WP_OPTION_INTEGRATE_WCCUSTOMERDATA'           => 'integrate-woocommerce-customer-data',
		'GTM4WP_OPTION_INTEGRATE_WCORDERDATA'              => 'integrate-woocommerce-order-data',
		'GTM4WP_OPTION_INTEGRATE_WCORDERMAXAGE'            => 'integrate-woocommerce-order-max-age',
		'GTM4WP_OPTION_INTEGRATE_WCEXCLUDETAX'             => 'integrate-woocommerce-exclude-tax',
		'GTM4WP_OPTION_INTEGRATE_WCEXCLUDESHIPPING'        => 'integrate-woocommerce-exclude-shipping',
		'GTM4WP_OPTION_INTEGRATE_WCNOORDERTRACKEDFLAG'     => 'integrate-woocommerce-do-not-use-order-tracked-flag',
		'GTM4WP_OPTION_INTEGRATE_WCCLEARECOMMERCEDL'       => 'integrate-woocommerce-clear-ecommerce-datalayer',
		'GTM4WP_OPTION_INTEGRATE_WCDLMAXTIMEOUT'           => 'integrate-woocommerce-datalayer-max-timeout',
		'GTM4WP_OPTION_INTEGRATE_WCTRANSACTIONIDPREFIX'    => 'integrate-woocommerce-transaction-id-prefix',
		'GTM4WP_OPTION_INTEGRATE_WCPURCHASESTATUSES'       => 'integrate-woocommerce-purchase-track-statuses',
		'GTM4WP_OPTION_INTEGRATE_WCPURCHASEONANYPAGE'      => 'integrate-woocommerce-purchase-track-on-any-page',
		'GTM4WP_OPTION_INTEGRATE_WCCUSTOMORDERRECEIVEDPAGE' => 'integrate-woocommerce-custom-order-received-page',
		'GTM4WP_OPTION_INTEGRATE_WCLISTATTRIBUTION'        => 'integrate-woocommerce-persist-list-attribution',
		'GTM4WP_OPTION_INTEGRATE_WC_CHECKOUTWC'            => 'integrate-woocommerce-checkoutwc',
		'GTM4WP_OPTION_INTEGRATE_WCMASTERLANGUAGE'         => 'integrate-woocommerce-master-language',
		'GTM4WP_OPTION_INTEGRATE_EDDTRACKECOMMERCE'        => 'integrate-edd-track-ecommerce',
		'GTM4WP_OPTION_INTEGRATE_EDDPRODPERIMPRESSION'     => 'integrate-edd-product-per-impression',
		'GTM4WP_OPTION_INTEGRATE_EDDINCLUDECARTINDL'       => 'integrate-edd-cart-content-in-datalayer',
		'GTM4WP_OPTION_INTEGRATE_EDDBRANDTAXONOMY'         => 'integrate-edd-brand-taxonomy',
		'GTM4WP_OPTION_INTEGRATE_EDDBUSINESSVERTICAL'      => 'integrate-edd-business-vertical',
		'GTM4WP_OPTION_INTEGRATE_EDDUSESKU'                => 'integrate-edd-use-sku',
		'GTM4WP_OPTION_INTEGRATE_EDDUSEFULLCATEGORYPATH'   => 'integrate-edd-use-full-category-path',
		'GTM4WP_OPTION_INTEGRATE_EDDMASTERLANGUAGE'        => 'integrate-edd-master-language',
		'GTM4WP_OPTION_INTEGRATE_EDDPRODIDPREFIX'          => 'integrate-edd-product-id-prefix',
		'GTM4WP_OPTION_INTEGRATE_EDDCUSTOMERDATA'          => 'integrate-edd-customer-data',
		'GTM4WP_OPTION_INTEGRATE_EDDORDERDATA'             => 'integrate-edd-order-data',
		'GTM4WP_OPTION_INTEGRATE_EDDORDERMAXAGE'           => 'integrate-edd-order-max-age',
		'GTM4WP_OPTION_INTEGRATE_EDDEXCLUDETAX'            => 'integrate-edd-exclude-tax',
		'GTM4WP_OPTION_INTEGRATE_EDDNOORDERTRACKEDFLAG'    => 'integrate-edd-do-not-use-order-tracked-flag',
		'GTM4WP_OPTION_INTEGRATE_EDDCLEARECOMMERCEDL'      => 'integrate-edd-clear-ecommerce-datalayer',
		'GTM4WP_OPTION_INTEGRATE_EDDDLMAXTIMEOUT'          => 'integrate-edd-datalayer-max-timeout',
		'GTM4WP_OPTION_INTEGRATE_EDDTRANSACTIONIDPREFIX'   => 'integrate-edd-transaction-id-prefix',
		'GTM4WP_OPTION_INTEGRATE_EDDPURCHASESTATUSES'      => 'integrate-edd-purchase-track-statuses',
		'GTM4WP_OPTION_INTEGRATE_EDDTRACKONANYPAGE'        => 'integrate-edd-purchase-track-on-any-page',
		'GTM4WP_OPTION_INTEGRATE_EDDLISTATTRIBUTION'       => 'integrate-edd-persist-list-attribution',
		'GTM4WP_OPTION_GDM_DESTINATIONS'                   => 'gdm-destinations',
		'GTM4WP_OPTION_GDM_CONSENT_POLICY'                 => 'gdm-consent-policy',
		'GTM4WP_OPTION_GDM_SEND_REFUNDS'                   => 'gdm-send-refunds',
		'GTM4WP_OPTION_INTEGRATE_WPECOMMERCE'              => 'integrate-wp-e-commerce',
		'GTM4WP_OPTION_INTEGRATE_AMPID'                    => 'integrate-amp-id',
		'GTM4WP_OPTION_INTEGRATE_COOKIEBOT'                => 'integrate-cookiebot',
		'GTM4WP_OPTION_INTEGRATE_WEBTOFFEE_GDPR'           => 'integrate-webtoffee-gdpr',
		'GTM4WP_OPTION_INTEGRATE_COOKIEYES'                => 'integrate-cookieyes',
		'GTM4WP_OPTION_INTEGRATE_AXEPTIO'                  => 'integrate-axeptio',
		'GTM4WP_OPTION_INTEGRATE_AXEPTIO_PROJECTID'        => 'integrate-axeptio-projectid',
		'GTM4WP_OPTION_INTEGRATE_AXEPTIO_COOKIES_VERSION'  => 'integrate-axeptio-cookies-version',
		'GTM4WP_OPTION_INTEGRATE_AXEPTIO_CONSENTMODE'      => 'integrate-axeptio-consent-mode',
		'GTM4WP_OPTION_INTEGRATE_CONSENTMODE'              => 'integrate-consent-mode',
		'GTM4WP_OPTION_INTEGRATE_CONSENTMODE_ADS'          => 'integrate-consent-mode-ads',
		'GTM4WP_OPTION_INTEGRATE_CONSENTMODE_AD_USER_DATA' => 'integrate-consent-mode-ad-user-data',
		'GTM4WP_OPTION_INTEGRATE_CONSENTMODE_AD_PERSO'     => 'integrate-consent-mode-ad-perso',
		'GTM4WP_OPTION_INTEGRATE_CONSENTMODE_ANALYTICS'    => 'integrate-consent-mode-analytics',
		'GTM4WP_OPTION_INTEGRATE_CONSENTMODE_PERSO'        => 'integrate-consent-mode-perso',
		'GTM4WP_OPTION_INTEGRATE_CONSENTMODE_FUNC'         => 'integrate-consent-mode-func',
		'GTM4WP_OPTION_INTEGRATE_CONSENTMODE_SECURUTY'     => 'integrate-consent-mode-security',
		'GTM4WP_PLACEMENT_FOOTER'                          => 0,
		'GTM4WP_PLACEMENT_BODYOPEN'                        => 1,
		'GTM4WP_PLACEMENT_BODYOPEN_AUTO'                   => 2,
		'GTM4WP_PLACEMENT_OFF'                             => 3,
		'GTM4WP_WPFILTER_COMPILE_DATALAYER'                => 'gtm4wp_compile_datalayer',
		'GTM4WP_WPACTION_AFTER_DATALAYER'                  => 'gtm4wp_output_after_datalayer',
		'GTM4WP_WPACTION_AFTER_CONTAINER_CODE'             => 'gtm4wp_after_container_code',
		'GTM4WP_WPFILTER_OUTPUT_CONTAINER'                 => 'gtm4wp_output_container',
		'GTM4WP_WPFILTER_ADDGLOBALVARS_ARRAY'              => 'gtm4wp_add_global_vars_array',
		'GTM4WP_WPFILTER_VISITOR_SCOPED_FIELDS'            => 'gtm4wp_visitor_scoped_fields',
		'GTM4WP_WPFILTER_GET_CSP_NONCE'                    => 'gtm4wp_get_csp_nonce',
		'GTM4WP_WPFILTER_OVERWRITE_COMO_FLAG'              => 'gtm4wp_overwrite_consent_mode_flag',
		'GTM4WP_WPFILTER_AXEPTIO_CONSENT_MODE_DEFAULT'     => 'gtm4wp_axeptio_consent_mode_default',
		'GTM4WP_WPFILTER_EEC_PRODUCT_ARRAY'                => 'gtm4wp_eec_product_array',
		'GTM4WP_WPFILTER_EEC_ITEM_WITH_SOURCE'             => 'gtm4wp_eec_item_with_source',
		'GTM4WP_WPFILTER_EEC_CART_ITEM'                    => 'gtm4wp_eec_cart_item',
		'GTM4WP_WPFILTER_EEC_ORDER_ITEM'                   => 'gtm4wp_eec_order_item',
		'GTM4WP_WPFILTER_EEC_ORDER_DATA'                   => 'gtm4wp_eec_order_data',
		'GTM4WP_WPFILTER_EEC_ITEM_AFFILIATION'             => 'gtm4wp_eec_item_affiliation',
		'GTM4WP_WPFILTER_ECC_PURCHASE_DATALAYER'           => 'gtm4wp_purchase_datalayer',
		'GTM4WP_WPFILTER_EEC_DATALAYER_PAGELOAD'           => 'gtm4wp_woocommerce_datalayer_on_pageload',
		'GTM4WP_WPFILTER_EEC_EDD_CART_ITEM'                => 'gtm4wp_eec_edd_cart_item',
		'GTM4WP_WPFILTER_EEC_EDD_ORDER_ITEM'               => 'gtm4wp_eec_edd_order_item',
		'GTM4WP_WPFILTER_EEC_EDD_ORDER_DATA'               => 'gtm4wp_eec_edd_order_data',
		'GTM4WP_WPFILTER_EDD_PURCHASE_DATALAYER'           => 'gtm4wp_edd_purchase_datalayer',
		'GTM4WP_WPFILTER_EDD_DATALAYER_PAGELOAD'           => 'gtm4wp_edd_datalayer_on_pageload',
		'GTM4WP_WPFILTER_EDD_ORDER_PHONE'                  => 'gtm4wp_edd_order_phone',
		'GTM4WP_WPFILTER_GOOGLE_SERVICE_ACCOUNT_IN_USE'    => 'gtm4wp_google_service_account_in_use',
		'GTM4WP_WPFILTER_GDM_DESTINATIONS'                 => 'gtm4wp_gdm_destinations',
		'GTM4WP_WPFILTER_GDM_ORDER_CONSENT'                => 'gtm4wp_gdm_order_consent',
		'GTM4WP_WPFILTER_GDM_REFUND_EVENT'                 => 'gtm4wp_gdm_refund_event',
		'GTM4WP_WPFILTER_ABILITIES_ENABLED'                => 'gtm4wp_abilities_enabled',
		'GTM4WP_WPFILTER_ABILITIES_ALLOW_WRITE'            => 'gtm4wp_abilities_allow_write',
	);

	public function test_every_public_constant_keeps_its_value(): void {
		foreach ( self::VALUES as $name => $value ) {
			$this->assertTrue( defined( $name ), $name );
			$this->assertSame( $value, constant( $name ), $name );
		}
	}

	public function test_the_table_lists_every_constant_the_file_defines(): void {
		$source = (string) file_get_contents( dirname( __DIR__, 3 ) . '/compat/constants.php' ); // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents -- local source file, not a remote URL.

		preg_match_all( "/^define\\( '([A-Z0-9_]+)'/m", $source, $matches );

		$this->assertSame( array_keys( self::VALUES ), $matches[1], 'Add the new constant to VALUES with its literal value.' );
	}
}
