<?php
/**
 * GENERATED FILE - DO NOT EDIT BY HAND.
 *
 * Regenerate with: composer generate:phone-table
 * Source: Google libphonenumber, resources/PhoneNumberMetadata.xml
 * Generated: 2026-08-11
 *
 * @package GTM4WP
 * @author Thomas Geiger
 * @copyright 2013- Geiger Tamás e.v. (Thomas Geiger s.e.)
 * @license GNU General Public License, version 3
 */

namespace GTM4WP\Modules\WooCommerce;

defined( 'ABSPATH' ) || exit;

/**
 * Per-country calling code and national (trunk) prefix, used to turn a locally
 * typed phone number into E.164 before hashing it for Enhanced Conversions.
 *
 * A null prefix is NOT "unknown" - it means the country has no trunk prefix at
 * all, so a leading zero is part of the number and must be kept. Italy is the
 * best-known case; six more behave the same way. Conflating that with "uses 0"
 * is what made every Italian landline hash to a value Google could never match.
 *
 * See tools/generate-phone-table.php for why this is generated rather than
 * written, and what it deliberately does not model.
 */
final class CountryPhoneData {

	/**
	 * ISO 3166-1 alpha-2 code => array( calling code, national prefix or null ).
	 *
	 * 144 of the entries have a trunk prefix; the rest have none.
	 *
	 * @var array<string, array{0: string, 1: string|null}>
	 */
	private const COUNTRIES = array(
		'AC' => array( '247', null ),
		'AD' => array( '376', null ),
		'AE' => array( '971', '0' ),
		'AF' => array( '93', '0' ),
		'AG' => array( '1', '1' ),
		'AI' => array( '1', '1' ),
		'AL' => array( '355', '0' ),
		'AM' => array( '374', '0' ),
		'AO' => array( '244', null ),
		'AR' => array( '54', '0' ),
		'AS' => array( '1', '1' ),
		'AT' => array( '43', '0' ),
		'AU' => array( '61', '0' ),
		'AW' => array( '297', null ),
		'AX' => array( '358', '0' ),
		'AZ' => array( '994', '0' ),
		'BA' => array( '387', '0' ),
		'BB' => array( '1', '1' ),
		'BD' => array( '880', '0' ),
		'BE' => array( '32', '0' ),
		'BF' => array( '226', null ),
		'BG' => array( '359', '0' ),
		'BH' => array( '973', null ),
		'BI' => array( '257', null ),
		'BJ' => array( '229', null ),
		'BL' => array( '590', '0' ),
		'BM' => array( '1', '1' ),
		'BN' => array( '673', null ),
		'BO' => array( '591', '0' ),
		'BQ' => array( '599', null ),
		'BR' => array( '55', '0' ),
		'BS' => array( '1', '1' ),
		'BT' => array( '975', null ),
		'BW' => array( '267', null ),
		'BY' => array( '375', '8' ),
		'BZ' => array( '501', null ),
		'CA' => array( '1', '1' ),
		'CC' => array( '61', '0' ),
		'CD' => array( '243', '0' ),
		'CF' => array( '236', null ),
		'CG' => array( '242', null ),
		'CH' => array( '41', '0' ),
		'CI' => array( '225', null ),
		'CK' => array( '682', null ),
		'CL' => array( '56', null ),
		'CM' => array( '237', null ),
		'CN' => array( '86', '0' ),
		'CO' => array( '57', '0' ),
		'CR' => array( '506', null ),
		'CU' => array( '53', '0' ),
		'CV' => array( '238', null ),
		'CW' => array( '599', null ),
		'CX' => array( '61', '0' ),
		'CY' => array( '357', null ),
		'CZ' => array( '420', null ),
		'DE' => array( '49', '0' ),
		'DJ' => array( '253', null ),
		'DK' => array( '45', null ),
		'DM' => array( '1', '1' ),
		'DO' => array( '1', '1' ),
		'DZ' => array( '213', '0' ),
		'EC' => array( '593', '0' ),
		'EE' => array( '372', null ),
		'EG' => array( '20', '0' ),
		'EH' => array( '212', '0' ),
		'ER' => array( '291', '0' ),
		'ES' => array( '34', null ),
		'ET' => array( '251', '0' ),
		'FI' => array( '358', '0' ),
		'FJ' => array( '679', null ),
		'FK' => array( '500', null ),
		'FM' => array( '691', null ),
		'FO' => array( '298', null ),
		'FR' => array( '33', '0' ),
		'GA' => array( '241', null ),
		'GB' => array( '44', '0' ),
		'GD' => array( '1', '1' ),
		'GE' => array( '995', '0' ),
		'GF' => array( '594', '0' ),
		'GG' => array( '44', '0' ),
		'GH' => array( '233', '0' ),
		'GI' => array( '350', null ),
		'GL' => array( '299', null ),
		'GM' => array( '220', null ),
		'GN' => array( '224', null ),
		'GP' => array( '590', '0' ),
		'GQ' => array( '240', null ),
		'GR' => array( '30', null ),
		'GT' => array( '502', null ),
		'GU' => array( '1', '1' ),
		'GW' => array( '245', null ),
		'GY' => array( '592', null ),
		'HK' => array( '852', null ),
		'HN' => array( '504', null ),
		'HR' => array( '385', '0' ),
		'HT' => array( '509', null ),
		'HU' => array( '36', '06' ),
		'ID' => array( '62', '0' ),
		'IE' => array( '353', '0' ),
		'IL' => array( '972', '0' ),
		'IM' => array( '44', '0' ),
		'IN' => array( '91', '0' ),
		'IO' => array( '246', null ),
		'IQ' => array( '964', '0' ),
		'IR' => array( '98', '0' ),
		'IS' => array( '354', null ),
		'IT' => array( '39', null ),
		'JE' => array( '44', '0' ),
		'JM' => array( '1', '1' ),
		'JO' => array( '962', '0' ),
		'JP' => array( '81', '0' ),
		'KE' => array( '254', '0' ),
		'KG' => array( '996', '0' ),
		'KH' => array( '855', '0' ),
		'KI' => array( '686', '0' ),
		'KM' => array( '269', null ),
		'KN' => array( '1', '1' ),
		'KP' => array( '850', '0' ),
		'KR' => array( '82', '0' ),
		'KW' => array( '965', null ),
		'KY' => array( '1', '1' ),
		'KZ' => array( '7', '8' ),
		'LA' => array( '856', '0' ),
		'LB' => array( '961', '0' ),
		'LC' => array( '1', '1' ),
		'LI' => array( '423', '0' ),
		'LK' => array( '94', '0' ),
		'LR' => array( '231', '0' ),
		'LS' => array( '266', null ),
		'LT' => array( '370', '0' ),
		'LU' => array( '352', null ),
		'LV' => array( '371', null ),
		'LY' => array( '218', '0' ),
		'MA' => array( '212', '0' ),
		'MC' => array( '377', '0' ),
		'MD' => array( '373', '0' ),
		'ME' => array( '382', '0' ),
		'MF' => array( '590', '0' ),
		'MG' => array( '261', '0' ),
		'MH' => array( '692', '1' ),
		'MK' => array( '389', '0' ),
		'ML' => array( '223', null ),
		'MM' => array( '95', '0' ),
		'MN' => array( '976', '0' ),
		'MO' => array( '853', null ),
		'MP' => array( '1', '1' ),
		'MQ' => array( '596', '0' ),
		'MR' => array( '222', null ),
		'MS' => array( '1', '1' ),
		'MT' => array( '356', null ),
		'MU' => array( '230', null ),
		'MV' => array( '960', null ),
		'MW' => array( '265', '0' ),
		'MX' => array( '52', null ),
		'MY' => array( '60', '0' ),
		'MZ' => array( '258', null ),
		'NA' => array( '264', '0' ),
		'NC' => array( '687', null ),
		'NE' => array( '227', null ),
		'NF' => array( '672', null ),
		'NG' => array( '234', '0' ),
		'NI' => array( '505', null ),
		'NL' => array( '31', '0' ),
		'NO' => array( '47', null ),
		'NP' => array( '977', '0' ),
		'NR' => array( '674', null ),
		'NU' => array( '683', null ),
		'NZ' => array( '64', '0' ),
		'OM' => array( '968', null ),
		'PA' => array( '507', null ),
		'PE' => array( '51', '0' ),
		'PF' => array( '689', null ),
		'PG' => array( '675', null ),
		'PH' => array( '63', '0' ),
		'PK' => array( '92', '0' ),
		'PL' => array( '48', null ),
		'PM' => array( '508', '0' ),
		'PR' => array( '1', '1' ),
		'PS' => array( '970', '0' ),
		'PT' => array( '351', null ),
		'PW' => array( '680', null ),
		'PY' => array( '595', '0' ),
		'QA' => array( '974', null ),
		'RE' => array( '262', '0' ),
		'RO' => array( '40', '0' ),
		'RS' => array( '381', '0' ),
		'RU' => array( '7', '8' ),
		'RW' => array( '250', '0' ),
		'SA' => array( '966', '0' ),
		'SB' => array( '677', null ),
		'SC' => array( '248', null ),
		'SD' => array( '249', '0' ),
		'SE' => array( '46', '0' ),
		'SG' => array( '65', null ),
		'SH' => array( '290', null ),
		'SI' => array( '386', '0' ),
		'SJ' => array( '47', null ),
		'SK' => array( '421', '0' ),
		'SL' => array( '232', '0' ),
		'SM' => array( '378', null ),
		'SN' => array( '221', null ),
		'SO' => array( '252', '0' ),
		'SR' => array( '597', null ),
		'SS' => array( '211', '0' ),
		'ST' => array( '239', null ),
		'SV' => array( '503', null ),
		'SX' => array( '1', '1' ),
		'SY' => array( '963', '0' ),
		'SZ' => array( '268', null ),
		'TA' => array( '290', null ),
		'TC' => array( '1', '1' ),
		'TD' => array( '235', null ),
		'TG' => array( '228', null ),
		'TH' => array( '66', '0' ),
		'TJ' => array( '992', null ),
		'TK' => array( '690', null ),
		'TL' => array( '670', null ),
		'TM' => array( '993', '8' ),
		'TN' => array( '216', null ),
		'TO' => array( '676', null ),
		'TR' => array( '90', '0' ),
		'TT' => array( '1', '1' ),
		'TV' => array( '688', null ),
		'TW' => array( '886', '0' ),
		'TZ' => array( '255', '0' ),
		'UA' => array( '380', '0' ),
		'UG' => array( '256', '0' ),
		'US' => array( '1', '1' ),
		'UY' => array( '598', '0' ),
		'UZ' => array( '998', null ),
		'VA' => array( '39', null ),
		'VC' => array( '1', '1' ),
		'VE' => array( '58', '0' ),
		'VG' => array( '1', '1' ),
		'VI' => array( '1', '1' ),
		'VN' => array( '84', '0' ),
		'VU' => array( '678', null ),
		'WF' => array( '681', null ),
		'WS' => array( '685', null ),
		'XK' => array( '383', '0' ),
		'YE' => array( '967', '0' ),
		'YT' => array( '262', '0' ),
		'ZA' => array( '27', '0' ),
		'ZM' => array( '260', '0' ),
		'ZW' => array( '263', '0' ),
	);

	/**
	 * Looks up a country's dialling facts.
	 *
	 * @param string $country_code ISO 3166-1 alpha-2 code, any case, may be padded.
	 * @return array{0: string, 1: string|null}|null Calling code and national prefix,
	 *                                               or null when the country is unknown.
	 */
	public static function lookup( string $country_code ): ?array {
		$country_code = strtoupper( trim( $country_code ) );

		return self::COUNTRIES[ $country_code ] ?? null;
	}
}
